CREATE TABLE geral.proponente (
	id_proponente SERIAL PRIMARY KEY,
	razao_social VARCHAR(100),
	cnpj VARCHAR(14),
	nome_fantasia VARCHAR(100),
	web_site VARCHAR(80),
	email VARCHAR(80),
	celular VARCHAR(14),
	telefone_fixo VARCHAR(14),
	telefone_outro VARCHAR(14),
	responsavel_legal VARCHAR(200),
	cpf_responsavel VARCHAR(14),
	rg_responsavel VARCHAR(10),
	nome_social VARCHAR(100),
	data_nascimento TIMESTAMP DEFAULT NULL,
	cargo VARCHAR(100),
	cep_responsavel VARCHAR(9),
	logradouro_responsavel VARCHAR(100),
	numero_responsavel INT,
	complemento_responsavel VARCHAR(50),
	bairro_responsavel VARCHAR(50),
	cidade_responsavel VARCHAR(50),
	uf_responsavel VARCHAR(2),
	cep_pj VARCHAR(9),
	logradouro_pj VARCHAR(100),
	numero_pj INT,
	complemento_pj VARCHAR(50),
	bairro_pj VARCHAR(50),
	cidade_pj VARCHAR(50),
	uf_pj VARCHAR(2)
)